### PR TITLE
ClickHouse Functionality from branch

### PR DESCRIPTION
**Pull request by JSchoenbachler**

### CODE REVIEW

**Comment by jakejh** [comment]
First stuff that jumps out at me:
- Add space between `if` and `(...`.
- The R folder should only contain functions defined in the package, no scripts. That's what the data-raw folder is for. Everything in the R folder gets run when the package is built.
- Make sure to update the documentation, the description file, and the readme (to install RClickhouse from GitHub).

**Review by jakejh — CHANGES_REQUESTED** [review]
- For consistency, switch from `"MergeTree"` to `MergeTree()` everywhere.
- Switch from `\'` to `"` for readability.
- Convert lines 65-81 in utilities.R to a separate function `setNaToSpecial` that gets called by `appendTable`.

**Comment by JSchoenbachler** [comment]
I made the updates per your request except for point 2 in the first comment. I didn't add any files to the R folder and don't see anything outside of what was already there.

**Comment by JSchoenbachler** [comment]
Also, don't merge this yet. I'm looking into an issue with doing multiple files at once. It somehow entered into an "else" statement when checking to see if it was clickhouse, so it did the wrong query for some reason?

**Comment by jakejh** [comment]
Per the R folder comment, then remove the R/example_rep_script.R from gitignore.

**Review by jakejh — CHANGES_REQUESTED** [review]
Still missing a few things:
- still one instance of `if(`
- RClickhouse in Suggests of description file
- updated documentation for `modifyPubmedDb` (at the top of modify_pubmed_db.R), particularly the `@param dbtype`. In the `@return` section, describe the peculiarities of dates in Clickhouse. See the parseElement documentation for how to make paragraphs.
- if the `setNAToSpecial` is changing values by reference, then `appendTable` should just have `setNAToSpecial(d)` instead of `d = setNA...`.

In `setNAToSpecial`:
- why does the first `if` need `d[1]` instead of just `d`, if we already know there's only one row?
- return the data.table invisibly
- assign `as.Date('2100-01-01')` to a variable at the top of the function
- switch double quotes to single quotes
- switch `d[[column]] = val` to `d[, (column) := val]`

**Comment by jakejh** [comment]
Be sure to update the circleci config for R 4.0.2 and to install RClickhouse from GitHub.

**Comment by JSchoenbachler** [comment]
Made all changes except this:

why does the first if need d[1] instead of just d, if we already know there's only one row?

I have that so we don't do any unnecessary steps. For instance, if there is only 1 row  but all columns are filled in, it wouldn't go through the slew of if statements that just do nothing. Would you rather me just remove it?

**Comment by jakejh** [comment]
I'm not questioning the logic, just saying that if there's only one row, then `d[1L]` can be simplified to `d`, right?

**Comment by JSchoenbachler** [comment]
Updated.

**Comment by jakejh** [comment]
Did you see my comment about the circleci config?

**Comment by JSchoenbachler** [comment]
Made the update to circleCI config. Had to revert where you wanted me to just use

`setNAToSpecial(d)`

instead of 

`d = setNAToSpecial(d)`

since it wasn't actually modifying d. Did I do something wrong there?

**Comment by jakejh** [comment]
The function is definitely modifying `d` by reference, see below. On a separate point, you could change `d[, (column) := val]` to `d[, (column) := val][]`.

``` r
library(data.table)
d = data.table(pmid = 1L, text = NA)
pmparser:::setNAToSpecial(d)
d[]
#>    pmid text
#> 1:    1    0
```

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JSchoenbachler** [comment]
That's weird. I had it the way you did there but it was still giving me the error that there were values that were null. I'll try again and make sure it wasn't just a weird fluke.

**Comment by jakejh** [comment]
Make sure the function is catching all the types of NA.

**Comment by JSchoenbachler** [comment]
Okay, will do. Also, am I doing something wrong? I reverted to not setting d equal to the output of the function and it still isn't modifying it.
What I have now:
```
appendTable = function(con, tableName, d) {
  if (is.null(con) || nrow(d) == 0L) return(invisible())
  if (inherits(con, what='ClickhouseConnection')){
    setNAToSpecial(d)}
  # for some reason dbWriteTable is faster than dbAppendTable
  DBI::dbWriteTable(con, tableName, d, append = TRUE)}
```
and the function is
```
setNAToSpecial = function(d) {
  naDateVal = as.Date('2100-01-01')
  if (nrow(d) == 1L && any(is.na(d))){
    columns = colnames(d)
    for(column in columns){
      if (is.na(d[[column]])){
        if (is.logical(d[[column]])) val = 0
        else if (is.integer(d[[column]])) val = -1L
        else if (is.numeric(d[[column]])) val = -1
        else if (inherits(d[[column]], 'POSIXct')) val = naDateVal
        else if (inherits(d[[column]], 'Date')) val = naDateVal
        else val = as.character(NA)
        d[, (column) := val]}}
  } else {
    for (j in 1:ncol(d)) {
      if (inherits(d[[j]], 'Date')) {
        data.table::set(
          d, i = which(is.na(d[[j]])), j = j, value = naDateVal)}}}
  return(invisible(d))
}
```

For whatever reason, this prompts an error with clickhouse meanwhile if I do the assignment (`d = setNAToSpecial(d)`) it works.

**Comment by JSchoenbachler** [comment]
Nevermind, RStudio was just being weird. Disregard.

**Comment by JSchoenbachler** [comment]
Closing to clean up.

**Pull request closed without merging**
