### PR TITLE
Pub year abstract pos

### PR DESCRIPTION
**Pull request by JSchoenbachler**
Adds abstract_pos column and sets `pub_year` to extracted year from `medline_date` if null.

### CODE REVIEW

**Comment by jakejh** [comment]
Looks good. Is there any way we can avoid adding `stringr` as a dependency though? It can be tricky to compile on Linux while using conda.

**Comment by jakejh** [comment]
What about something like this?

```r
x2[is.na(pub_year), date_idx := regexpr('[0-9]{4}', medline_date)]
x2[is.na(pub_year) & date_idx > 0,
   pub_year := as.integer(substr(medline_date, date_idx, date_idx + 3L))]
x2[, date_idx := NULL]
```

**Comment by JSchoenbachler** [comment]
That works, but also what about this:
```
x22[is.na(pub_year) & grepl('[0-9]{4}', medline_date),
    pub_year := as.integer(
      substr(medline_date,
             regexpr('[0-9]{4}', medline_date),
             regexpr('[0-9]{4}', medline_date) + 3L))]
```
It would keep it all in one call, and not require setting a column just to subsequently remove that column.

**Comment by jakejh** [comment]
Yes, but what's the tradeoff?

**Comment by JSchoenbachler** [comment]
The fact that it recalculates 2 additional times instead of just once for the column, I guess. We can just take your method!

It's also worth noting that when I ran a query to check, there was no instance in which both `pub_year` and `medline_date` were empty. Although, I didn't then check to see if `medline_date` had a year in every instance.

**Comment by jakejh** [comment]
Right. Probably won't make a big difference here, but in general I like to avoid calculating the same thing more than once.

**Comment by JSchoenbachler** [comment]
Alright, your code has replaced my old code and the dependency has been removed!

**Review by jakejh — APPROVED** [review]

**Pull request merged**
